//! A person living in the economy.
//!
//! The first human being in the simulation. Everything until now has been
//! a world — terrain, nations, markets, freight — with populations as
//! numbers. This is one individual inside it, with money, hunger, a skill
//! and somewhere to be.
//!
//! Three rules from the design carry the whole thing, and they are what
//! make this a person in a world rather than a character in a game:
//!
//! - **Nothing is pushed** (spec A4.1). Work exists as a fact in the
//!   world — a haul somebody needs doing — and is found by being in the
//!   right market to hear of it. No quest markers, because there are no
//!   quests.
//! - **Nothing scales to the player.** Contracts are generated by the
//!   economy's own arithmetic, not by what this person can handle. Most
//!   are out of reach, already taken, or not worth the trip.
//! - **The world does not wait.** A contract heard of last week is gone.
//!
//! What a person does *not* have yet: a body, a position finer than which
//! market they are in, relationships, beliefs, or a life beyond earning
//! and eating. Those are specced (A3, B1, B6) and unbuilt.

use crate::econ::{Commodity, Economy};

/// Days a person can go hungry before it kills them.
///
/// Real starvation takes weeks — about forty days without food, far less
/// without water. What bites long before death is the weakness: a hungry
/// person works badly and cannot take heavy work at all.
const DAYS_TO_STARVE: f64 = 45.0;

/// What one person eats a day, from the same real figure the markets use:
/// 0.40 t of processed food a year.
pub const FOOD_PER_DAY: f64 = 0.40 / 365.0;

/// A trade a person can work at. Deliberately a handful, not B1.1's
/// hundred — the point is that a skill gates what work can be taken, and
/// one example proves that as well as ninety do.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Trade {
    /// Drives a lorry. Entry-level freight work, per spec A4.9.
    Haulier,
    /// Works a shift at a mill or cannery.
    Labourer,
}

impl Trade {
    pub fn name(self) -> &'static str {
        match self {
            Trade::Haulier => "haulier",
            Trade::Labourer => "labourer",
        }
    }
}

/// Work somebody wants done, posted because the economy wants it done.
#[derive(Clone, Debug)]
pub struct Contract {
    pub kind: Job,
    /// Day it appeared, and the day after which nobody wants it any more.
    pub posted: u64,
    pub expires: u64,
    /// What it pays, in full, on completion.
    pub pay: f64,
    /// Days of work it takes.
    pub days: f64,
    pub trade: Trade,
}

#[derive(Clone, Debug)]
pub enum Job {
    /// Move somebody else's goods along a route for a wage. The margin is
    /// theirs; the driver is paid by the day, and ends up at the far end.
    Haul {
        route: usize,
        commodity: Commodity,
        tonnes: f64,
        from_market: usize,
        to_market: usize,
    },
    /// **Buy the cargo yourself.**
    ///
    /// The same journey, but on your own account: you pay for the goods at
    /// this end and sell at the other, so the margin is yours and so is
    /// the risk. It needs capital, which is what a wage is for, and the
    /// price can move against you while you are on the road — which is
    /// what makes it a decision rather than a better wage.
    Venture {
        route: usize,
        commodity: Commodity,
        tonnes: f64,
        from_market: usize,
        to_market: usize,
        /// What the load cost, paid on setting out.
        outlay: f64,
    },
    /// A shift at a works that has orders to fill.
    Shift { site: usize, market: usize },
}

impl Contract {
    pub fn describe(&self, econ: &Economy) -> String {
        match &self.kind {
            Job::Haul {
                commodity,
                tonnes,
                from_market,
                to_market,
                ..
            } => format!(
                "haul {tonnes:.0} t of {commodity} from {} to {} — {:.0} over {:.1} days",
                econ.markets[*from_market].name,
                econ.markets[*to_market].name,
                self.pay,
                self.days,
            ),
            Job::Venture {
                commodity,
                tonnes,
                from_market,
                to_market,
                outlay,
                ..
            } => format!(
                "bought {tonnes:.1} t of {commodity} for {outlay:.0} to sell in {} \
                 ({:.1} days on the road)",
                econ.markets[*to_market].name,
                self.days,
            )
            .replace("  ", " ")
                + &format!(" — from {}", econ.markets[*from_market].name),
            Job::Shift { site, .. } => format!(
                "a shift at {} — {:.0} for {:.1} days",
                econ.ledger.sites[*site].name, self.pay, self.days,
            ),
        }
    }

    /// Money that must be found before the work can be taken.
    pub fn stake(&self) -> f64 {
        match &self.kind {
            Job::Venture { outlay, .. } => *outlay,
            _ => 0.0,
        }
    }

    /// Pay per day of work, which is how anyone actually compares two jobs.
    pub fn daily_rate(&self) -> f64 {
        self.pay / self.days.max(0.01)
    }
}

/// How a person is getting on.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum State {
    Idle,
    Working { until: u64 },
    Dead,
}

pub struct Person {
    pub name: String,
    pub trade: Trade,
    /// Which market they are in. The finest position anyone has yet.
    pub market: usize,
    pub money: f64,
    /// Days of food in hand.
    pub larder: f64,
    /// 0 (starving) to 1 (fed). Falls when there is nothing to eat.
    pub condition: f64,
    pub state: State,
    /// The contract in hand, if any.
    pub job: Option<Contract>,
    /// What has happened to them. The beginning of B4's memory log.
    pub log: Vec<String>,
    pub days_hungry: u64,
    pub days_worked: u64,
    pub earned: f64,
}

impl Person {
    pub fn new(name: impl Into<String>, trade: Trade, market: usize, money: f64) -> Self {
        Person {
            name: name.into(),
            trade,
            market,
            money,
            larder: 3.0,
            condition: 1.0,
            state: State::Idle,
            job: None,
            log: Vec::new(),
            days_hungry: 0,
            days_worked: 0,
            earned: 0.0,
        }
    }

    pub fn alive(&self) -> bool {
        self.state != State::Dead
    }

    fn note(&mut self, day: u64, what: impl Into<String>) {
        self.log.push(format!("day {day}: {}", what.into()));
    }
}

// ---------------------------------------------------------------------------
// Work that exists because the economy wants it done
// ---------------------------------------------------------------------------

/// Wage per day for a trade, from what the work is worth.
///
/// Labour share of output is 50-60% in reality (spec A.8), so a day's pay
/// tracks a day's production value. Scarcity of the specific skill would
/// move this; there is only one worker so far, so it does not.
pub fn day_rate(econ: &Economy, market: usize, trade: Trade) -> f64 {
    day_rate_for_food(econ, market, trade)
}

fn day_rate_for_food(econ: &Economy, market: usize, trade: Trade) -> f64 {
    // Anchored to what a day's food costs, which is what a wage has to
    // cover before anything else.
    let food = econ.price(market, Commodity::ProcessedFood) * FOOD_PER_DAY;
    let multiple = match trade {
        // Driving is entry-level freight work; a shift at a works pays a
        // little less for less risk and no lorry.
        Trade::Haulier => 3.2,
        Trade::Labourer => 2.6,
    };
    food * multiple
}

/// Every piece of work on offer in `market` today.
///
/// Generated from the economy's own state, never for anybody's benefit: a
/// haul exists when moving goods along a route is worth more than the
/// freight, and a shift exists when a works has the inputs to run and
/// somewhere to put the output. If the arithmetic does not say so, there
/// is no work, and a person who needs work is simply out of luck.
/// Work on offer in `market`, for somebody with `purse` to stake.
///
/// The purse matters because a venture is only on offer to a person who
/// can buy the load. That is not the world adapting to the player — the
/// cargo costs what it costs — it is the plain fact that you cannot trade
/// on your own account with empty pockets. A man with nothing sees only
/// wages, which is the point.
pub fn work_available(econ: &Economy, market: usize, day: u64, purse: f64) -> Vec<Contract> {
    let mut out = Vec::new();

    // Hauls: the arbitrage the trade system is already finding, offered as
    // a job rather than executed invisibly.
    for r in 0..econ.routes.len() {
        let route = &econ.routes[r];
        if !route.usable() || (route.a != market && route.b != market) {
            continue;
        }
        for &c in Commodity::ALL.iter() {
            if !c.storable() {
                continue;
            }
            let margin = econ.arbitrage(r, c);
            if margin <= 0.0 {
                continue;
            }
            let (from, to) = if econ.price(route.b, c) > econ.price(route.a, c) {
                (route.a, route.b)
            } else {
                (route.b, route.a)
            };
            // A lorry-load, not a shipload. The rest of the arbitrage is
            // somebody else's to take — but only out of what the sending
            // town will actually part with, or the job is a wage for
            // driving an empty lorry over a hill.
            let tonnes = 24.0f64
                .min(route.capacity * 0.02)
                .min(econ.surplus(from, c))
                .max(0.0);
            if tonnes < 0.2 {
                continue;
            }
            let days = (route.freight_cost / 40.0).clamp(1.0, 14.0);

            // **The driver is paid a wage, not the margin.**
            //
            // The margin belongs to whoever owns the cargo, and a driver
            // does not. Paying it to the haulier made one load worth two
            // years of a man's food and turned the job into a money
            // printer — which is not a bug in the arithmetic so much as a
            // misunderstanding of who is being paid for what. Somebody who
            // wants the margin has to buy the goods first and carry the
            // risk of the price moving under them, which is the trader's
            // path and a different, later thing.
            //
            // A haul on a route the merchant is making good money on pays
            // a little over the going rate, because he can afford it and
            // wants it done today.
            let rate = day_rate_for_food(econ, market, Trade::Haulier);
            let keenness = (1.0 + margin / c.base_cost()).clamp(1.0, 1.6);
            out.push(Contract {
                kind: Job::Haul {
                    route: r,
                    commodity: c,
                    tonnes,
                    from_market: from,
                    to_market: to,
                },
                posted: day,
                // Work goes to whoever is there. A haul nobody takes
                // within a week has been taken by somebody else.
                expires: day + 7,
                pay: rate * days * keenness,
                days,
                trade: Trade::Haulier,
            });

            // The same journey on your own account. Anyone with the money
            // to buy a load takes the margin instead of the wage — and the
            // risk of the price having moved by the time they arrive.
            //
            // How much load is what the purse buys, which is why this
            // starts as a sack on a cart and becomes a lorry only after
            // years of wages. The progression is the capital.
            // You can only buy what is actually for sale. A market quotes
            // a price for everything, including things it has none of and
            // things it is holding back, and offering a venture against
            // either stakes money on a cargo that will never be loaded.
            let for_sale = econ.surplus(from, c);

            let unit = econ.price(from, c).max(1e-6);
            let affordable = (purse / unit).min(tonnes).min(for_sale);
            if affordable >= 0.2 {
                let outlay = unit * affordable;
                out.push(Contract {
                    kind: Job::Venture {
                        route: r,
                        commodity: c,
                        tonnes: affordable,
                        from_market: from,
                        to_market: to,
                        outlay,
                    },
                    posted: day,
                    expires: day + 7,
                    // Expected, not guaranteed: what it fetches is whatever
                    // the far market will pay on the day it arrives.
                    pay: econ.price(to, c) * affordable,
                    days,
                    trade: Trade::Haulier,
                });
            }
        }
    }

    // Routine haulage: the ordinary freight of the country.
    //
    // Arbitrage is the interesting kind of haul and almost none of the real
    // kind. Most of what a lorry does is move a firm's own stock to where
    // the firm wants it, with no price gap involved at all — and offering
    // only the arbitrage hauls left a driver in a city of sixteen million
    // with nothing to do for four months, which starved him. The work
    // exists because the freight exists.
    //
    // It still is not a gift: it pays the going rate and no more, and it
    // only appears where a town genuinely has a surplus of something and
    // its neighbour has room for it.
    for r in 0..econ.routes.len() {
        let route = &econ.routes[r];
        if !route.usable() || (route.a != market && route.b != market) {
            continue;
        }
        let other = if route.a == market { route.b } else { route.a };
        let days = (route.freight_cost / 40.0).clamp(1.0, 14.0);
        let rate = day_rate_for_food(econ, market, Trade::Haulier);

        // Whatever this town has most to spare of, in the judgement of the
        // people who own it.
        let load = Commodity::ALL
            .iter()
            .copied()
            .filter(|c| c.storable())
            .map(|c| (c, econ.surplus(market, c).min(24.0)))
            .filter(|&(_, t)| t >= 0.2)
            .max_by(|a, b| a.1.total_cmp(&b.1).then((b.0 as usize).cmp(&(a.0 as usize))));
        let Some((c, tonnes)) = load else { continue };

        out.push(Contract {
            kind: Job::Haul {
                route: r,
                commodity: c,
                tonnes,
                from_market: market,
                to_market: other,
            },
            posted: day,
            expires: day + 7,
            pay: rate * days,
            days,
            trade: Trade::Haulier,
        });
    }

    // Shifts: a works that can run wants hands.
    for s in 0..econ.ledger.sites.len() {
        let site = &econ.ledger.sites[s];
        if site.market != market || site.recipe.is_none() || !site.powered {
            continue;
        }
        out.push(Contract {
            kind: Job::Shift { site: s, market },
            posted: day,
            expires: day + 3,
            pay: day_rate(econ, market, Trade::Labourer) * 6.0,
            days: 6.0,
            trade: Trade::Labourer,
        });
    }

    out.sort_by(|a, b| b.daily_rate().total_cmp(&a.daily_rate()));
    out
}

/// Move a load that a person actually carried.
///
/// Goes through the journal like every other change, so a lorry-load Hal
/// drove is the same tonnes arriving as left, and the conservation check
/// covers his work as it covers everything else.
/// Returns the tonnage that actually moved, which may be less than was
/// wanted and may be nothing at all.
///
/// Settling on the intended load rather than the delivered one pays a
/// trader for goods that were never there: a market with no stock of
/// something still quotes a price for it, and buying from an empty
/// warehouse turned a venture into free money.
fn deliver(
    econ: &mut Economy,
    commodity: Commodity,
    tonnes: f64,
    from_market: usize,
    to_market: usize,
) -> f64 {
    use crate::econ::Event;

    // Take it from whoever in the sending market has most of it, and give
    // it to whoever in the receiving market has room.
    let pick = |econ: &Economy, market: usize, most: bool| -> Option<usize> {
        (0..econ.ledger.sites.len())
            .filter(|&s| {
                econ.ledger.sites[s].market == market
                    && econ.ledger.sites[s].capacity[commodity as usize] > 0.0
            })
            .max_by(|&a, &b| {
                let score = |s: usize| {
                    if most {
                        econ.ledger.stock(s, commodity)
                    } else {
                        econ.ledger.sites[s].capacity[commodity as usize]
                            - econ.ledger.stock(s, commodity)
                    }
                };
                score(a).total_cmp(&score(b)).then(b.cmp(&a))
            })
    };

    let (Some(src), Some(dst)) = (pick(econ, from_market, true), pick(econ, to_market, false))
    else {
        return 0.0;
    };
    let room = (econ.ledger.sites[dst].capacity[commodity as usize]
        - econ.ledger.stock(dst, commodity))
    .max(0.0);
    // Nobody sells a town's working reserve at the going rate, and that
    // holds for a man with a lorry as much as for a firm. Without it the
    // most profitable trade in the country is always to strip whichever
    // town is shortest of what it is shortest of.
    let qty = tonnes
        .min(econ.ledger.stock(src, commodity))
        .min(econ.surplus(from_market, commodity))
        .min(room);
    if qty <= 1e-9 {
        return 0.0;
    }
    let mut journal = std::mem::take(&mut econ.journal);
    econ.ledger.apply(
        &mut journal,
        Event::Shipped {
            from: src,
            to: dst,
            commodity,
            qty,
        },
    );
    econ.journal = journal;
    qty
}

// ---------------------------------------------------------------------------
// A day in a life
// ---------------------------------------------------------------------------

/// Live one day: eat, work if working, look for work if not.
///
/// Order matters and is the order a day happens in. You eat before you
/// decide anything, because hunger is what decides it.
pub fn live_a_day(person: &mut Person, econ: &mut Economy, day: u64) {
    if !person.alive() {
        return;
    }

    // --- Eat ---
    if person.larder >= 1.0 {
        person.larder -= 1.0;
        person.condition = (person.condition + 0.08).min(1.0);
        person.days_hungry = 0;
    } else {
        // Buy if there is food to be had and money to buy it with. Prices
        // are the market's, not a shop menu's, so a shortage prices a poor
        // person out before it runs the shelves bare.
        let price = econ.price(person.market, Commodity::ProcessedFood);
        let week = price * FOOD_PER_DAY * 7.0;
        if person.money >= week {
            person.money -= week;
            person.larder += 7.0;
            person.larder -= 1.0;
            person.condition = (person.condition + 0.08).min(1.0);
            person.days_hungry = 0;
        } else if person.money >= price * FOOD_PER_DAY {
            person.money -= price * FOOD_PER_DAY;
            person.condition = (person.condition + 0.04).min(1.0);
            person.days_hungry = 0;
        } else {
            person.days_hungry += 1;
            person.condition = (person.condition - 1.0 / DAYS_TO_STARVE).max(0.0);
            if person.days_hungry == 1 {
                person.note(day, "went hungry — could not afford a day's food");
            }
            if person.condition <= 0.0 {
                person.state = State::Dead;
                person.note(day, "died of hunger");
                return;
            }
        }
    }

    // --- Work, or look for it ---
    match person.state {
        State::Working { until } if day < until => {}
        State::Working { .. } => {
            if let Some(job) = person.job.take() {
                // The work has to actually happen, or the world never
                // notices it was done. A haul that pays but moves nothing
                // leaves the price gap open, so the same job is offered
                // again tomorrow and for ever — a treadmill rather than an
                // economy.
                match job.kind {
                    Job::Haul {
                        commodity,
                        tonnes,
                        from_market,
                        to_market,
                        ..
                    } => {
                        deliver(econ, commodity, tonnes, from_market, to_market);
                        person.money += job.pay;
                        person.earned += job.pay;
                        // A driver ends up where the load was going.
                        person.market = to_market;
                        person.note(
                            day,
                            format!(
                                "delivered to {}, paid {:.0} — {:.0} in hand",
                                econ.markets[to_market].name, job.pay, person.money
                            ),
                        );
                    }
                    Job::Venture {
                        commodity,
                        tonnes,
                        from_market,
                        to_market,
                        outlay,
                        ..
                    } => {
                        // Only what was actually carried can be sold, and
                        // only what was carried was paid for: a warehouse
                        // that has sold out since the deal was struck hands
                        // the money back rather than keeping it for goods
                        // it never loaded. Settling on the intended load
                        // instead of the delivered one paid a trader for
                        // cargo that was never there, which turned a
                        // venture into free money.
                        let carried = deliver(econ, commodity, tonnes, from_market, to_market);
                        let unfilled = 1.0 - (carried / tonnes.max(1e-9)).clamp(0.0, 1.0);
                        person.money += outlay * unfilled;
                        // **Sold at whatever the market gives today**, not
                        // at the price that made the trip look worth
                        // taking. Days have passed; the price has moved.
                        // That gap is the whole risk of trading on your own
                        // account, and it can go either way.
                        let got = econ.price(to_market, commodity) * carried;
                        person.money += got;
                        let spent = outlay * (1.0 - unfilled);
                        let profit = got - spent;
                        person.earned += profit;
                        person.market = to_market;
                        person.note(
                            day,
                            format!(
                                "sold {carried:.1} t of {commodity} in {} for {got:.0} \
                                 ({}{:.0} on the venture) — {:.0} in hand",
                                econ.markets[to_market].name,
                                if profit >= 0.0 { "+" } else { "" },
                                profit,
                                person.money
                            ),
                        );
                        if profit < 0.0 {
                            person.note(day, "the price had moved against him");
                        }
                    }
                    Job::Shift { .. } => {
                        person.money += job.pay;
                        person.earned += job.pay;
                        person.note(
                            day,
                            format!(
                                "finished the shift, paid {:.0} — {:.0} in hand",
                                job.pay, person.money
                            ),
                        );
                    }
                }
            }
            person.state = State::Idle;
        }
        State::Idle => {
            let reserve_for_food = econ.price(person.market, Commodity::ProcessedFood)
                * FOOD_PER_DAY
                * 30.0;
            let stakeable = (person.money - reserve_for_food).max(0.0);
            let offers = work_available(econ, person.market, day, stakeable);
            // Take the best work this person is trained for, can afford to
            // stake, and is well enough to do. Never stake so much that a
            // bad trip leaves nothing to eat with — which is what keeps a
            // careful man alive and is also why the poor stay on wages.
            let reserve = econ.price(person.market, Commodity::ProcessedFood)
                * FOOD_PER_DAY
                * 30.0;
            let taken = offers.into_iter().find(|c| {
                c.trade == person.trade
                    && (person.condition > 0.4 || c.days <= 3.0)
                    && c.stake() <= (person.money - reserve).max(0.0)
            });
            if let Some(c) = taken {
                person.money -= c.stake();
                person.note(day, format!("took work: {}", c.describe(econ)));
                person.state = State::Working {
                    until: day + c.days.ceil() as u64,
                };
                person.days_worked += c.days.ceil() as u64;
                person.job = Some(c);
            } else if person.days_hungry > 0 {
                person.note(day, "found no work");
            }
        }
        State::Dead => {}
    }
}
