//! A person living in the economy.
//!
//! The first human being in the simulation. Everything until now has been
//! a world — terrain, nations, markets, freight — with populations as
//! numbers. This is one individual inside it, with money, hunger, a skill
//! and somewhere to be.
//!
//! Three rules from the design carry the whole thing, and they are what
//! make this a person in a world rather than a character in a game:
//!
//! - **Nothing is pushed** (spec A4.1). Work exists as a fact in the
//!   world — a haul somebody needs doing — and is found by being in the
//!   right market to hear of it. No quest markers, because there are no
//!   quests.
//! - **Nothing scales to the player.** Contracts are generated by the
//!   economy's own arithmetic, not by what this person can handle. Most
//!   are out of reach, already taken, or not worth the trip.
//! - **The world does not wait.** A contract heard of last week is gone.
//!
//! What a person does *not* have yet: a body, a position finer than which
//! market they are in, relationships, beliefs, or a life beyond earning
//! and eating. Those are specced (A3, B1, B6) and unbuilt.

use crate::econ::{Commodity, Economy};
use crate::travel::Conveyance;

/// Days a person can go hungry before it kills them.
///
/// Real starvation takes weeks — about forty days without food, far less
/// without water. What bites long before death is the weakness: a hungry
/// person works badly and cannot take heavy work at all.
const DAYS_TO_STARVE: f64 = 45.0;

/// What one person eats a day, from the same real figure the markets use:
/// 0.40 t of processed food a year.
pub const FOOD_PER_DAY: f64 = 0.40 / 365.0;

/// A trade a person can work at. Deliberately a handful, not B1.1's
/// hundred — the point is that a skill gates what work can be taken, and
/// one example proves that as well as ninety do.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Trade {
    /// Drives a lorry. Entry-level freight work, per spec A4.9.
    Haulier,
    /// Works a shift at a mill or cannery.
    Labourer,
}

impl Trade {
    pub fn name(self) -> &'static str {
        match self {
            Trade::Haulier => "haulier",
            Trade::Labourer => "labourer",
        }
    }
}

/// Work somebody wants done, posted because the economy wants it done.
#[derive(Clone, Debug)]
pub struct Contract {
    pub kind: Job,
    /// Day it appeared, and the day after which nobody wants it any more.
    pub posted: u64,
    pub expires: u64,
    /// What it pays, in full, on completion.
    pub pay: f64,
    /// Days of work it takes.
    pub days: f64,
    pub trade: Trade,
}

#[derive(Clone, Debug)]
pub enum Job {
    /// Move somebody else's goods along a route for a wage. The margin is
    /// theirs; the driver is paid by the day, and ends up at the far end.
    Haul {
        route: usize,
        commodity: Commodity,
        tonnes: f64,
        from_market: usize,
        to_market: usize,
    },
    /// **Buy the cargo yourself.**
    ///
    /// The same journey, but on your own account: you pay for the goods at
    /// this end and sell at the other, so the margin is yours and so is
    /// the risk. It needs capital, which is what a wage is for, and the
    /// price can move against you while you are on the road — which is
    /// what makes it a decision rather than a better wage.
    Venture {
        route: usize,
        commodity: Commodity,
        tonnes: f64,
        from_market: usize,
        to_market: usize,
        /// What the load cost, paid on setting out. Refundable in the sense
        /// that goods never loaded were never paid for.
        outlay: f64,
        /// Fodder, fuel and wear for the journey. Spent whether or not
        /// there turned out to be anything to carry, which is exactly what
        /// makes a wasted trip hurt.
        running: f64,
    },
    /// A shift at a works that has orders to fill.
    Shift { site: usize, market: usize },
}

impl Contract {
    pub fn describe(&self, econ: &Economy) -> String {
        match &self.kind {
            Job::Haul {
                commodity,
                tonnes,
                from_market,
                to_market,
                ..
            } => format!(
                "haul {tonnes:.0} t of {commodity} from {} to {} — {:.0} over {:.1} days",
                econ.markets[*from_market].name,
                econ.markets[*to_market].name,
                self.pay,
                self.days,
            ),
            Job::Venture {
                commodity,
                tonnes,
                from_market,
                to_market,
                outlay,
                ..
            } => format!(
                "bought {tonnes:.1} t of {commodity} for {outlay:.0} to sell in {} \
                 ({:.1} days on the road)",
                econ.markets[*to_market].name,
                self.days,
            )
            .replace("  ", " ")
                + &format!(" — from {}", econ.markets[*from_market].name),
            Job::Shift { site, market } if *site == usize::MAX => format!(
                "a day carting about {} — {:.0}",
                econ.markets[*market].name, self.pay,
            ),
            Job::Shift { site, .. } => format!(
                "a shift at {} — {:.0} for {:.1} days",
                econ.ledger.sites[*site].name, self.pay, self.days,
            ),
        }
    }

    /// Money that must be found before the work can be taken.
    ///
    /// The cargo *and* the journey. You need the fodder before you set off,
    /// not after you arrive — and charging the running cost against the
    /// profit while never taking it out of the purse handed him free
    /// diesel, which is the same money printer wearing a different hat.
    pub fn stake(&self) -> f64 {
        match &self.kind {
            Job::Venture {
                outlay, running, ..
            } => *outlay + *running,
            _ => 0.0,
        }
    }

    /// Pay per day of work, which is how anyone actually compares two jobs.
    pub fn daily_rate(&self) -> f64 {
        self.pay / self.days.max(0.01)
    }
}

/// How a person is getting on.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum State {
    Idle,
    Working { until: u64 },
    Dead,
}

pub struct Person {
    pub name: String,
    pub trade: Trade,
    /// Which market they are in. The finest position anyone has yet.
    pub market: usize,
    pub money: f64,
    /// Days of food in hand.
    pub larder: f64,
    /// 0 (starving) to 1 (fed). Falls when there is nothing to eat.
    pub condition: f64,
    pub state: State,
    /// **What they can move goods with, and therefore what they can trade.**
    ///
    /// A wage haul is driving somebody else's lorry, so it does not depend
    /// on this. Trading on your own account entirely does: a man on foot
    /// carries 35 kg over the pass, not twenty-four tonnes, and the road
    /// out of that is to buy a better vehicle rather than to find a better
    /// price.
    pub conveyance: Conveyance,
    /// The contract in hand, if any.
    pub job: Option<Contract>,
    /// What has happened to them. The beginning of B4's memory log.
    pub log: Vec<String>,
    pub days_hungry: u64,
    /// Days since he last had work. What actually drives someone to move.
    pub days_idle: u64,
    pub days_worked: u64,
    /// Days spent carrying his own cargo. What decides whether a vehicle
    /// is worth its keep — one that earns on twelve days a year and eats
    /// on three hundred and sixty-five is a way to go broke slowly.
    pub days_trading: u64,
    /// Gross takings: wages, and the profit on ventures after their costs.
    pub earned: f64,
    /// Everything that went out and did not come back — food eaten, and
    /// the vehicles bought. With these two, `money` reconciles exactly to
    /// what he started with, which is the nearest thing to a money ledger
    /// a person has yet.
    pub spent: f64,
}

impl Person {
    pub fn new(name: impl Into<String>, trade: Trade, market: usize, money: f64) -> Self {
        Person {
            name: name.into(),
            trade,
            market,
            money,
            larder: 3.0,
            condition: 1.0,
            state: State::Idle,
            conveyance: Conveyance::OnFoot,
            job: None,
            log: Vec::new(),
            days_hungry: 0,
            days_idle: 0,
            days_worked: 0,
            days_trading: 0,
            earned: 0.0,
            spent: 0.0,
        }
    }

    pub fn alive(&self) -> bool {
        self.state != State::Dead
    }

    fn note(&mut self, day: u64, what: impl Into<String>) {
        self.log.push(format!("day {day}: {}", what.into()));
    }
}

// ---------------------------------------------------------------------------
// Work that exists because the economy wants it done
// ---------------------------------------------------------------------------

/// Wage per day for a trade, from what the work is worth and how many
/// hands are chasing it.
///
/// Labour share of output is 50-60% in reality (spec A.8), so a day's pay
/// tracks a day's production value. On top of that sits the state of the
/// local labour market: **wages sag where the works are idle**, though not
/// nearly as far as the idleness itself, because nominal wages are sticky
/// and what really gives is whether anybody is hiring at all.
pub fn day_rate(econ: &Economy, market: usize, trade: Trade) -> f64 {
    let index = econ
        .workforce
        .get(market)
        .map(|w| w.wage_index)
        .unwrap_or(1.0);
    day_rate_for_food(econ, market, trade) * index
}

fn day_rate_for_food(econ: &Economy, market: usize, trade: Trade) -> f64 {
    // Anchored to what a day's food costs, which is what a wage has to
    // cover before anything else — but to the *settled* cost, not this
    // morning's. Pay is renegotiated once a year, so it lags a price
    // shock by months, and that lag is how a shock actually makes people
    // poorer. Tying it to today's price meant bread and wages quintupled
    // together in a blackout and nobody noticed one.
    let food = econ
        .workforce
        .get(market)
        .map(|w| w.food_anchor)
        .filter(|a| *a > 0.0)
        .unwrap_or_else(|| econ.price(market, Commodity::ProcessedFood) * FOOD_PER_DAY);
    // **Real low-wage work buys six to ten days of food for a day's
    // labour**, which is the same thing as saying the poorest households
    // spend something like a tenth to a sixth of their income on eating.
    // These sat at 2.6 and 3.2 — a third of the real figure, and the note
    // recording the real one had been in the project file the whole time.
    //
    // It is not a cosmetic error. At 2.6 a labourer who gets work three
    // days in five cannot feed himself working flat out, so nobody ever
    // saved for anything and every life ended a little poorer than it
    // began. Being *at* subsistence is the historical condition; being
    // permanently below it is not, or there would be nobody left.
    let multiple = match trade {
        // Driving is entry-level freight work; a shift at a works pays a
        // little less for less risk and no lorry.
        Trade::Haulier => 7.0,
        Trade::Labourer => 6.0,
    };
    food * multiple
}

/// Every piece of work on offer in `market` today.
///
/// Generated from the economy's own state, never for anybody's benefit: a
/// haul exists when moving goods along a route is worth more than the
/// freight, and a shift exists when a works has the inputs to run and
/// somewhere to put the output. If the arithmetic does not say so, there
/// is no work, and a person who needs work is simply out of luck.
/// Work on offer in `market`, for somebody with `purse` to stake.
///
/// The purse matters because a venture is only on offer to a person who
/// can buy the load. That is not the world adapting to the player — the
/// cargo costs what it costs — it is the plain fact that you cannot trade
/// on your own account with empty pockets. A man with nothing sees only
/// wages, which is the point.
pub fn work_available(
    econ: &Economy,
    market: usize,
    day: u64,
    purse: f64,
    conveyance: Conveyance,
) -> Vec<Contract> {
    let mut out = Vec::new();

    // Hauls: the arbitrage the trade system is already finding, offered as
    // a job rather than executed invisibly.
    for r in 0..econ.routes.len() {
        let route = &econ.routes[r];
        if !route.usable() || (route.a != market && route.b != market) {
            continue;
        }
        let surface = route.surface;
        for &c in Commodity::ALL.iter() {
            if !c.storable() {
                continue;
            }
            let margin = econ.arbitrage(r, c);
            if margin <= 0.0 {
                continue;
            }
            let (from, to) = if econ.price(route.b, c) > econ.price(route.a, c) {
                (route.a, route.b)
            } else {
                (route.b, route.a)
            };
            // A wage haul is driving the firm's lorry, so it moves a
            // lorry-load and travels at a lorry's speed whatever the driver
            // personally owns. The rest of the arbitrage is somebody
            // else's to take — and only out of what the sending town will
            // actually part with, or the job is a wage for driving an
            // empty lorry over a hill.
            let tonnes = Conveyance::Lorry
                .payload()
                .min(route.capacity * 0.02)
                .min(econ.surplus(from, c))
                .max(0.0);
            if tonnes < 0.2 {
                continue;
            }
            let Some(speed) = Conveyance::Lorry.km_per_day(surface) else {
                continue; // no lorry gets over this
            };
            let days = (route.km / speed).clamp(1.0, 60.0);

            // **The driver is paid a wage, not the margin.**
            //
            // The margin belongs to whoever owns the cargo, and a driver
            // does not. Paying it to the haulier made one load worth two
            // years of a man's food and turned the job into a money
            // printer — which is not a bug in the arithmetic so much as a
            // misunderstanding of who is being paid for what. Somebody who
            // wants the margin has to buy the goods first and carry the
            // risk of the price moving under them, which is the trader's
            // path and a different, later thing.
            //
            // A haul on a route the merchant is making good money on pays
            // a little over the going rate, because he can afford it and
            // wants it done today.
            let rate = day_rate(econ, market, Trade::Haulier);
            let keenness = (1.0 + margin / c.base_cost()).clamp(1.0, 1.6);
            out.push(Contract {
                kind: Job::Haul {
                    route: r,
                    commodity: c,
                    tonnes,
                    from_market: from,
                    to_market: to,
                },
                posted: day,
                // Work goes to whoever is there. A haul nobody takes
                // within a week has been taken by somebody else.
                expires: day + 7,
                pay: rate * days * keenness,
                days,
                trade: Trade::Haulier,
            });

            // The same journey on your own account. The margin is yours
            // instead of the wage — and so is the risk of the price having
            // moved by the time you arrive.
            //
            // **Two things bind, and both are real.** The purse says what
            // you can buy. The vehicle says what you can carry, and it is
            // usually the binding one: a man on foot takes 35 kg over the
            // pass however rich he is, and 35 kg of grain will not make
            // anybody's fortune. That is why the ladder out is a handcart
            // and then a mule and then a lorry, and why most people never
            // get past the first rung.
            //
            // You can also only buy what is actually for sale. A market
            // quotes a price for everything, including things it has none
            // of and things it is holding back, and offering a venture
            // against either stakes money on a cargo never loaded.
            let for_sale = econ.surplus(from, c);
            let Some(own_speed) = conveyance.km_per_day(surface) else {
                continue; // he cannot get there with what he has
            };
            let own_days = (route.km / own_speed).clamp(1.0, 120.0);

            let unit = econ.price(from, c).max(1e-6);
            let affordable = (purse / unit)
                .min(conveyance.payload())
                .min(for_sale);
            // Getting there costs something even before the cargo: fodder
            // for an animal that eats whether it earns or not, diesel for
            // a lorry that costs several times its driver's wage to run.
            let wage = day_rate(econ, market, Trade::Haulier);
            let running = conveyance.upkeep_in_wage_days(true) * wage * own_days;
            if affordable >= 0.005 {
                let outlay = unit * affordable;
                let days = own_days;
                out.push(Contract {
                    kind: Job::Venture {
                        route: r,
                        commodity: c,
                        tonnes: affordable,
                        from_market: from,
                        to_market: to,
                        outlay,
                        running,
                    },
                    posted: day,
                    expires: day + 7,
                    // Expected, not guaranteed: what it fetches is whatever
                    // the far market will pay on the day it arrives.
                    pay: econ.price(to, c) * affordable,
                    days,
                    trade: Trade::Haulier,
                });
            }
        }
    }

    // Routine haulage: the ordinary freight of the country.
    //
    // Arbitrage is the interesting kind of haul and almost none of the real
    // kind. Most of what a lorry does is move a firm's own stock to where
    // the firm wants it, with no price gap involved at all — and offering
    // only the arbitrage hauls left a driver in a city of sixteen million
    // with nothing to do for four months, which starved him. The work
    // exists because the freight exists.
    //
    // It still is not a gift: it pays the going rate and no more, and it
    // only appears where a town genuinely has a surplus of something and
    // its neighbour has room for it.
    for r in 0..econ.routes.len() {
        let route = &econ.routes[r];
        if !route.usable() || (route.a != market && route.b != market) {
            continue;
        }
        // **The cargo is whatever the economy actually shipped today.**
        //
        // Not something chosen from inventory: firms move their own stock
        // for their own reasons, and a driver is hired to drive it. Making
        // up loads from the biggest surplus had him shuttling the same
        // grain between the same two towns for a decade, out on Monday and
        // back on Tuesday, paid both ways and nobody any better off.
        let Some((c, to, shipped)) = route.moved else {
            continue;
        };
        if to == market {
            continue; // today's freight is coming *here*, not going
        }
        let other = to;
        let days = (route.freight_cost / 40.0).clamp(1.0, 14.0);
        let rate = day_rate(econ, market, Trade::Haulier);
        let tonnes = shipped.min(Conveyance::Lorry.payload());
        if tonnes < 0.2 {
            continue;
        }

        out.push(Contract {
            kind: Job::Haul {
                route: r,
                commodity: c,
                tonnes,
                from_market: market,
                to_market: other,
            },
            posted: day,
            expires: day + 7,
            pay: rate * days,
            days,
            trade: Trade::Haulier,
        });
    }

    // **Carting about the town.**
    //
    // Most freight is local and always was: grain from the farm to the
    // mill, flour from the mill to the cannery, tins from the cannery to
    // the shops. It is short, dull, and it is the bulk of what a lorry
    // actually does — a country moves several times more tonnage inside
    // its towns than between them.
    //
    // Leaving it out was why a haulier in a city of sixteen million could
    // find seventeen days of work in three years. Inter-town freight is
    // genuinely rare here, because every town in this economy has its own
    // farm and mill and cannery and so has little need of its neighbours —
    // which is a real gap in `region.rs`, not something to paper over with
    // invented long-distance loads.
    let working_town = econ
        .ledger
        .sites
        .iter()
        .any(|s| s.market == market && s.ran > 0.0);
    if working_town {
        let rate = day_rate(econ, market, Trade::Haulier);
        out.push(Contract {
            kind: Job::Shift {
                site: usize::MAX,
                market,
            },
            posted: day,
            expires: day + 1,
            pay: rate,
            days: 1.0,
            trade: Trade::Haulier,
        });
    }

    // Shifts: a works that **is running** wants hands.
    //
    // Not one that merely has power. A mill with no grain employs nobody
    // today, and a works standing idle is precisely where the jobs are
    // not — which is the whole reason the workforce is modelled.
    for s in 0..econ.ledger.sites.len() {
        let site = &econ.ledger.sites[s];
        if site.market != market || site.recipe.is_none() {
            continue;
        }
        // **A farm is not the grid's to shut, and neither are its jobs.**
        //
        // Two gates said otherwise and both were wrong the same way. A
        // works with no power offers no shifts, true — but a farm does not
        // stop for a blackout (spec A.2: its dependency is water), and it
        // has hands on it all year whether or not anything is being cut.
        // Between them these left a farm labourer with no work for months
        // when in fact there was plenty, and made a grid fault look like a
        // famine by a route that does not exist.
        let is_farm = site.kind == crate::econ::SiteKind::Farm;
        if !is_farm && (!site.powered || site.ran <= 0.0) {
            continue;
        }
        out.push(Contract {
            kind: Job::Shift { site: s, market },
            posted: day,
            expires: day + 3,
            pay: day_rate(econ, market, Trade::Labourer) * 6.0,
            days: 6.0,
            trade: Trade::Labourer,
        });
    }

    out.sort_by(|a, b| b.daily_rate().total_cmp(&a.daily_rate()));
    out
}

/// A number in 0..1 from who somebody is and what day it is.
///
/// Deterministic, because a seed has to rebuild the same world and the
/// same life forever. This is not luck in the sense of a dice roll the
/// player can reload away from — it is the part of getting hired that
/// nobody controls, and it has to be reproducible like everything else.
fn draw(name: &str, day: u64) -> f64 {
    let mut h = day.wrapping_mul(0x9E37_79B9_7F4A_7C15);
    for b in name.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x1000_0000_01B3);
    }
    h ^= h >> 29;
    h = h.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    h ^= h >> 32;
    (h >> 11) as f64 / (1u64 << 53) as f64
}

/// Move a load that a person actually carried.
///
/// Goes through the journal like every other change, so a lorry-load Hal
/// drove is the same tonnes arriving as left, and the conservation check
/// covers his work as it covers everything else.
/// Returns the tonnage that actually moved, which may be less than was
/// wanted and may be nothing at all.
///
/// Settling on the intended load rather than the delivered one pays a
/// trader for goods that were never there: a market with no stock of
/// something still quotes a price for it, and buying from an empty
/// warehouse turned a venture into free money.
fn deliver(
    econ: &mut Economy,
    commodity: Commodity,
    tonnes: f64,
    from_market: usize,
    to_market: usize,
) -> f64 {
    use crate::econ::Event;

    // Take it from whoever in the sending market has most of it, and give
    // it to whoever in the receiving market has room.
    let pick = |econ: &Economy, market: usize, most: bool| -> Option<usize> {
        (0..econ.ledger.sites.len())
            .filter(|&s| {
                econ.ledger.sites[s].market == market
                    && econ.ledger.sites[s].capacity[commodity as usize] > 0.0
            })
            .max_by(|&a, &b| {
                let score = |s: usize| {
                    if most {
                        econ.ledger.stock(s, commodity)
                    } else {
                        econ.ledger.sites[s].capacity[commodity as usize]
                            - econ.ledger.stock(s, commodity)
                    }
                };
                score(a).total_cmp(&score(b)).then(b.cmp(&a))
            })
    };

    let (Some(src), Some(dst)) = (pick(econ, from_market, true), pick(econ, to_market, false))
    else {
        return 0.0;
    };
    let room = (econ.ledger.sites[dst].capacity[commodity as usize]
        - econ.ledger.stock(dst, commodity))
    .max(0.0);
    // Nobody sells a town's working reserve at the going rate, and that
    // holds for a man with a lorry as much as for a firm. Without it the
    // most profitable trade in the country is always to strip whichever
    // town is shortest of what it is shortest of.
    let qty = tonnes
        .min(econ.ledger.stock(src, commodity))
        .min(econ.surplus(from_market, commodity))
        .min(room);
    if qty <= 1e-9 {
        return 0.0;
    }
    let mut journal = std::mem::take(&mut econ.journal);
    econ.ledger.apply(
        &mut journal,
        Event::Shipped {
            from: src,
            to: dst,
            commodity,
            qty,
        },
    );
    econ.journal = journal;
    qty
}

// ---------------------------------------------------------------------------
// A day in a life
// ---------------------------------------------------------------------------

/// Live one day: eat, work if working, look for work if not.
///
/// Order matters and is the order a day happens in. You eat before you
/// decide anything, because hunger is what decides it.
pub fn live_a_day(person: &mut Person, econ: &mut Economy, day: u64) {
    if !person.alive() {
        return;
    }

    // --- Eat ---
    if person.larder >= 1.0 {
        person.larder -= 1.0;
        person.condition = (person.condition + 0.08).min(1.0);
        person.days_hungry = 0;
    } else {
        // Buy if there is food to be had and money to buy it with. Prices
        // are the market's, not a shop menu's, so a shortage prices a poor
        // person out before it runs the shelves bare.
        let price = econ.price(person.market, Commodity::ProcessedFood);
        let week = price * FOOD_PER_DAY * 7.0;
        if person.money >= week {
            person.money -= week;
            person.spent += week;
            person.larder += 7.0;
            person.larder -= 1.0;
            person.condition = (person.condition + 0.08).min(1.0);
            person.days_hungry = 0;
        } else if person.money >= price * FOOD_PER_DAY {
            person.money -= price * FOOD_PER_DAY;
            person.spent += price * FOOD_PER_DAY;
            person.condition = (person.condition + 0.04).min(1.0);
            person.days_hungry = 0;
        } else {
            person.days_hungry += 1;
            person.condition = (person.condition - 1.0 / DAYS_TO_STARVE).max(0.0);
            if person.days_hungry == 1 {
                person.note(day, "went hungry — could not afford a day's food");
            }
            if person.condition <= 0.0 {
                person.state = State::Dead;
                person.note(day, "died of hunger");
                return;
            }
        }
    }

    // --- Keep what you own ---
    //
    // **A vehicle costs money on the days it earns none.** An animal eats
    // whether it works or not and a lorry has to be housed, taxed and
    // maintained; charging upkeep only while travelling let a man own a
    // lorry for nothing on the days he was driving somebody else's.
    {
        let standing = person.conveyance.upkeep_in_wage_days(false)
            * day_rate(econ, person.market, Trade::Haulier);
        if standing > 0.0 {
            let paid = standing.min(person.money.max(0.0));
            person.money -= paid;
            person.spent += paid;
        }
    }

    // --- Work, or look for it ---
    match person.state {
        State::Working { until } if day < until => {}
        State::Working { .. } => {
            if let Some(job) = person.job.take() {
                // The work has to actually happen, or the world never
                // notices it was done. A haul that pays but moves nothing
                // leaves the price gap open, so the same job is offered
                // again tomorrow and for ever — a treadmill rather than an
                // economy.
                match job.kind {
                    Job::Haul {
                        commodity,
                        tonnes,
                        from_market,
                        to_market,
                        ..
                    } => {
                        deliver(econ, commodity, tonnes, from_market, to_market);
                        person.money += job.pay;
                        person.earned += job.pay;
                        // A driver ends up where the load was going.
                        person.market = to_market;
                        person.note(
                            day,
                            format!(
                                "delivered to {}, paid {:.0} — {:.0} in hand",
                                econ.markets[to_market].name, job.pay, person.money
                            ),
                        );
                    }
                    Job::Venture {
                        commodity,
                        tonnes,
                        from_market,
                        to_market,
                        outlay,
                        running,
                        ..
                    } => {
                        // Only what was actually carried can be sold, and
                        // only what was carried was paid for: a warehouse
                        // that has sold out since the deal was struck hands
                        // the money back rather than keeping it for goods
                        // it never loaded. Settling on the intended load
                        // instead of the delivered one paid a trader for
                        // cargo that was never there, which turned a
                        // venture into free money.
                        let carried = deliver(econ, commodity, tonnes, from_market, to_market);
                        let unfilled = 1.0 - (carried / tonnes.max(1e-9)).clamp(0.0, 1.0);
                        // The cargo comes back as money if it was never
                        // loaded. The journey does not: the fodder was
                        // eaten and the fuel was burned getting there.
                        person.money += outlay * unfilled;
                        // **Sold at whatever the market gives today**, not
                        // at the price that made the trip look worth
                        // taking. Days have passed; the price has moved.
                        // That gap is the whole risk of trading on your own
                        // account, and it can go either way.
                        let got = econ.price(to_market, commodity) * carried;
                        person.money += got;
                        let spent = outlay * (1.0 - unfilled) + running;
                        let profit = got - spent;
                        person.earned += profit;
                        person.market = to_market;
                        person.note(
                            day,
                            format!(
                                "sold {carried:.1} t of {commodity} in {} for {got:.0} \
                                 ({}{:.0} on the venture) — {:.0} in hand",
                                econ.markets[to_market].name,
                                if profit >= 0.0 { "+" } else { "" },
                                profit,
                                person.money
                            ),
                        );
                        if profit < 0.0 {
                            person.note(day, "the price had moved against him");
                        }
                    }
                    Job::Shift { .. } => {
                        person.money += job.pay;
                        person.earned += job.pay;
                        person.note(
                            day,
                            format!(
                                "finished the shift, paid {:.0} — {:.0} in hand",
                                job.pay, person.money
                            ),
                        );
                    }
                }
            }
            person.state = State::Idle;
        }
        State::Idle => {
            let reserve_for_food = econ.price(person.market, Commodity::ProcessedFood)
                * FOOD_PER_DAY
                * 30.0;

            // --- Buy a better vehicle, if it is clearly worth it ---
            //
            // **This is the ladder.** Not a bigger purse: a bigger load.
            // A man on foot who saves for a barrow quadruples what he can
            // carry, and a man with a barrow who saves for years can buy a
            // lorry and carry a hundred and sixty times as much. The rungs
            // are far apart on purpose, because they are far apart in life.
            //
            // He buys only when he can pay for it and still keep a month's
            // food behind him, which is why the careful get there and the
            // desperate never do.
            {
                let wage = day_rate(econ, person.market, Trade::Haulier);
                let budget = (person.money - reserve_for_food * 2.0).max(0.0);
                // The ground he would actually be working. The worst road
                // out of this town, because that is the one that decides
                // whether wheels are any use.
                let surface = econ
                    .routes
                    .iter()
                    .filter(|r| r.usable() && (r.a == person.market || r.b == person.market))
                    .map(|r| r.surface)
                    .max_by_key(|s| *s as usize)
                    .unwrap_or(crate::econ::Surface::Road);
                let rate = econ
                    .routes
                    .iter()
                    .find(|r| r.a == person.market || r.b == person.market)
                    .map(|r| r.sound_cost / r.km.max(1.0))
                    .unwrap_or(0.26);
                // What a cargo costs, so a vehicle is judged on the load
                // he could actually put in it.
                let goods = econ.price(person.market, Commodity::Grain).max(1e-6);
                // How much of his life he actually spends trading on his
                // own account. A man three months into the job has no
                // record, so give him the benefit of a modest doubt.
                let seen = (person.days_worked + person.days_idle).max(1) as f64;
                let usage = if seen < 90.0 {
                    0.25
                } else {
                    person.days_trading as f64 / seen
                };
                if let Some((better, price)) = Conveyance::best_upgrade(
                    person.conveyance,
                    budget,
                    wage,
                    surface,
                    rate,
                    goods,
                    usage,
                ) {
                    person.money -= price;
                    person.spent += price;
                    person.conveyance = better;
                    person.note(
                        day,
                        format!(
                            "bought {} for {price:.0} — carries {:.0} kg now, {:.0} in hand",
                            better.name(),
                            better.payload() * 1000.0,
                            person.money
                        ),
                    );
                }
            }

            let stakeable = (person.money - reserve_for_food).max(0.0);
            let offers = work_available(econ, person.market, day, stakeable, person.conveyance);
            // Take the best work this person is trained for, can afford to
            // stake, and is well enough to do. Never stake so much that a
            // bad trip leaves nothing to eat with — which is what keeps a
            // careful man alive and is also why the poor stay on wages.
            let reserve = econ.price(person.market, Commodity::ProcessedFood)
                * FOOD_PER_DAY
                * 30.0;
            // **Somebody else may get it.**
            //
            // A slack labour market does not mainly feel like low wages,
            // it feels like not being taken on. Where there are more hands
            // than posts, the work goes to one of them and not the others,
            // and which one is not a thing anybody chooses — so it is
            // drawn, deterministically, from who he is and what day it is.
            //
            // **A venture is exempt, and that matters.** Nobody hires you
            // to trade on your own account, so working for yourself is the
            // way out of a town with no work in it — which is exactly why
            // a vehicle is worth saving for.
            let hiring = econ
                .workforce
                .get(person.market)
                .map(|w| w.chance_of_work())
                .unwrap_or(1.0);
            let drawn = draw(&person.name, day);
            let taken = offers.into_iter().find(|c| {
                let hired = c.stake() > 0.0 || drawn < hiring;
                c.trade == person.trade
                    && hired
                    && (person.condition > 0.4 || c.days <= 3.0)
                    && c.stake() <= (person.money - reserve).max(0.0)
            });
            if let Some(c) = taken {
                person.days_idle = 0;
                if c.stake() > 0.0 {
                    person.days_trading += c.days.ceil() as u64;
                }
                person.money -= c.stake();
                person.note(day, format!("took work: {}", c.describe(econ)));
                person.state = State::Working {
                    until: day + c.days.ceil() as u64,
                };
                person.days_worked += c.days.ceil() as u64;
                person.job = Some(c);
            } else {
                // **When a town stops working, people leave it.**
                //
                // He sat in a place at 89% unemployment and starved over
                // six weeks with a road out of it and the fare in his
                // pocket. That is not what anybody does. Migration is the
                // oldest response to a dead local economy and leaving it
                // out made the simulation quietly cruel in a way real life
                // is not — famine happens to people who *cannot* leave.
                //
                // He goes when work here has dried up and somewhere in
                // reach is visibly better, and he has to be able to afford
                // to get there and eat when he arrives. Somebody with
                // nothing is trapped, which is the real shape of it.
                person.days_idle += 1;
                let here = econ
                    .workforce
                    .get(person.market)
                    .map(|w| w.unemployment)
                    .unwrap_or(0.0);

                // **What actually drives somebody out is the bread price,
                // not the unemployment rate.**
                //
                // Nobody sees a statistic. What a man notices is that
                // there is no work this week and a loaf costs what a day
                // used to pay — and by the time an unemployment figure has
                // worked its way through three weeks of labour stickiness,
                // he is already too poor to buy his way out. Triggering on
                // the number he cannot see trapped him in a dying town
                // with the fare still in his pocket.
                let wage = day_rate(econ, person.market, person.trade);
                let bread = econ.price(person.market, Commodity::ProcessedFood) * FOOD_PER_DAY;
                let desperate = here > 0.25 || bread * 3.0 > wage || person.days_idle > 10;
                let moved = if desperate && person.condition > 0.35 {
                    leave_town(person, econ, day)
                } else {
                    false
                };
                if !moved && (person.days_idle == 3 || person.days_idle % 21 == 0) {
                    person.note(
                        day,
                        format!(
                            "{} days without work, bread at {bread:.2} against a wage of {wage:.2}",
                            person.days_idle
                        ),
                    );
                }
            }
        }
        State::Dead => {}
    }
}

/// Try to walk to a town with work in it. Returns whether he set off.
///
/// The journey is real: it takes as long as his own legs or wheels need,
/// and he eats on the way. That is what makes it a decision rather than a
/// teleport — a man who leaves it too late cannot afford the road.
fn leave_town(person: &mut Person, econ: &Economy, day: u64) -> bool {
    let food = econ.price(person.market, Commodity::ProcessedFood) * FOOD_PER_DAY;
    let mut best: Option<(usize, f64, f64, String)> = None;

    for r in econ.routes.iter() {
        if !r.usable() || (r.a != person.market && r.b != person.market) {
            continue;
        }
        let there = if r.a == person.market { r.b } else { r.a };
        let Some(speed) = person.conveyance.km_per_day(r.surface) else {
            continue;
        };
        let days = (r.km / speed).max(1.0).ceil();
        // He must be able to eat the whole way and still land with a few
        // days in hand, or the journey kills him rather than saving him.
        let fare = food * days * 1.5 + person.conveyance.upkeep_in_wage_days(true)
            * day_rate(econ, person.market, Trade::Haulier)
            * days;
        if fare > person.money {
            continue;
        }
        let Some(w) = econ.workforce.get(there) else {
            continue;
        };
        // Worth the trip only if it is meaningfully better than here.
        // He knows what a person could know: whether that town's works are
        // running, and what they charge for bread there — the second is
        // the thing travellers have always actually carried news of.
        let gain = econ.workforce[person.market].unemployment - w.unemployment;
        let cheaper = (food - econ.price(there, Commodity::ProcessedFood) * FOOD_PER_DAY)
            / food.max(1e-9);
        if gain < 0.15 && cheaper < 0.20 {
            continue;
        }
        let score = (gain + cheaper) / days;
        if best.as_ref().is_none_or(|(_, s, _, _)| score > *s) {
            best = Some((there, score, days, econ.markets[there].name.clone()));
        }
    }

    let Some((there, _, days, name)) = best else {
        return false;
    };
    let fare = food * days * 1.5;
    person.money -= fare;
    person.spent += fare;
    person.market = there;
    person.larder = (person.larder + days * 0.5).min(7.0);
    person.state = State::Working {
        until: day + days as u64,
    };
    person.job = None;
    person.note(
        day,
        format!(
            "left for {name} — {days:.0} days on the road, {:.0} in hand",
            person.money
        ),
    );
    true
}
